#!usr/bin/env ansible-playbook
---

- name: vm-php
  hosts: vm-php
  become: yes
  roles:
    - role: dotdeb-php7
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: geerlingguy.exim
    - role: geerlingguy.mailhog
    - role: dev-setup
